### ISSUE TITLE
RoR > Django ?

### ISSUE THREAD

**Issue by DonExo** [meshy/meshy.github.com#3]
It's not really a issue, but just curious why have you picked RoR for building your website, yet you are writing articles mostly about Django? :D

**Comment by meshy** [comment]
Hey @DonExo!

Well, github pages has a nice rails gem (called `github-pages`) that takes a lot of the work out of integrating with them, so it seemed like a good idea at the time!

I'm pretty sure it's [Jekyll](https://jekyllrb.com/) under the hood, if you're interested :smile:

**Comment by meshy** [comment]
As for Django, it's been my day-job for quite a while, so it's where I find most of my inspiration.

**Comment by meshy** [comment]
Oh! I just realised who you are!

I guess the fact that Django is my day-job is pretty obvious in hindsight! :joy:

**Comment by DonExo** [comment]
Oh, I was wondering if you ever will :D
Anyway, good to be back in touch mate, and good job with website. I've bookmarked some of your projects, so keep on rockin' with them ;)

We can consider now "this issue" as closed :D

**Comment by meshy** [comment]
Thanks! Hope you're well! :smile:
